---
abstract: 'Debian formatter for Changelogs'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ChangelogFromGit-Debian
requires:
  DateTime::Format::Mail: 0
  Dist::Zilla::Plugin::ChangelogFromGit: 0
  Moose: 0
  Text::Wrap: 0
resources:
  bugtracker: https://github.com/gphat/dist-zilla-plugin-changelogfromgit-debian/issues
  homepage: https://github.com/gphat/dist-zilla-plugin-changelogfromgit-debian
  repository: https://github.com/gphat/dist-zilla-plugin-changelogfromgit-debian.git
version: 0.10
